### ISSUE TITLE
Cannot create new topic after unsealing

### ISSUE THREAD

**Issue by lordvic1001** [balzack/databag#106]
I attempted to create a new topic and add users. Firstly, i was running an old version, but I created a new topic after unsealing and then only one user was there (just one federated, not local user). I unsealed and couldn't create a topic. Next, i re-pulled to latest as of 6/16/2024 and the behaviour remains the same. Presently, there is no sealing key in place, and it won't let me create a topic at all. It says i need to unseal (but it's unsealed).

![DB1](https://github.com/balzack/databag/assets/142373171/4b1d7fc1-7e37-41e7-8508-bff16749120f)

**Comment by balzack** [comment]
I think the issue is related to an admin setting added recently. Some admin's wanted to ensure all conversations are e2e encrypted, so that can be set in the dashboard now. I think 'allow unsealed' might be disabled for you (see screenshot). 

As for only 1 person showing up when you have the conversation sealed, it's likely the other users have not set up a sealing key, so no e2e 3ncrypted conversation with them is possible yet.

Please let me know if this doesn't address the problem.

<img width="404" alt="Screenshot 2024-06-16 at 6 09 24 PM" src="https://github.com/balzack/databag/assets/96387156/df9a008d-4b67-4183-a669-c84603a4b050">

**Comment by lordvic1001** [comment]
That resolved the issue. Thank you so much.
