### ISSUE TITLE
Chat selector doesn't open if share picture via gallery / file explorer

### ISSUE THREAD

**Issue by samuraikid0** [balzack/databag#55]
If I send a picture inside the app it works, 
If I send a picture from gallery share button, it opens databag but doesn't open the chat selection to be able to send the message

[logcat.txt](https://github.com/balzack/databag/files/12139591/logcat.txt)

Thanks !

**Comment by balzack** [comment]
I am not able to reproduce on my linageOS phone, but your logcat gives me a good clue where to look.

Thank you, hopefully I will find the problem soon.

**Comment by samuraikid0** [comment]
Great !
yes, it's a small issue the app is functional for use

Thanks !

**Comment by balzack** [comment]
thanks for being so great and supportive!

**Comment by balzack** [comment]
Just to let you know, i'm not making much progress on this issue. I thought the null pointer exception was a strong clue, but it turns out I see that error in my logs as well, and the chat selector pops up for me.

I'll keep trying to reproduce on my devices as I probably wont be able to fix this until I do so. I know it's not a critical issue for you, but I still want to fix it.

**Comment by samuraikid0** [comment]
Ok no problem
I'm currently waiting for some upgrade stuff,  I'll let you know once I've all setup

Thanks !

**Comment by samuraikid0** [comment]
Already I've tested again today and it's working now
 it could had been an OS issue

Thanks!
